theme: jekyll-theme-minimal
logo: avatar.jpg
title: マリウス
description: I’m a maker and full-time traveller with a love for decentralized technology, open-source, photography and coffee.
show_downloads: "false"
