theme: jekyll-theme-minimal
logo: avatar.jpg
title: マリウス
description: 🇪🇺 European 👔 CEO @twostairs 💻 Hacking #NLP/#AI & #FinTech 🐯 Adventurer 🎒 #Minimalist ☕️ Amateur barista ✈ Frequent flyer
show_downloads: "false"
google_analytics: UA-42605714-6
